CREATE TYPE ROLE AS ENUM ('tech_admin', 'junior', 'senior');

CREATE TABLE IF NOT EXISTS users(
  id UUID PRIMARY KEY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  firstname VARCHAR NOT NULL,
  lastname VARCHAR NOT NULL,
  role ROLE NOT NULL,
  email VARCHAR NOT NULL UNIQUE,
  updated_at TIMESTAMP WITH TIME ZONE NULL,
  accepted_at TIMESTAMP WITH TIME ZONE NULL,
  password VARCHAR NOT NULL
);

INSERT INTO
  users
VALUES
  (
    '72a911c8-ad24-4e2d-8930-9c3ba51741df',
    '2023-06-30T16:02:51+05:00',
    'Maftunbek',
    'Raxmatov',
    'tech_admin',
    'admin@scala.uz',
    null,
    '2023-06-30T16:02:51+05:00',
    '$s0$e0801$5JK3Ogs35C2h5htbXQoeEQ==$N7HgNieSnOajn1FuEB7l4PhC6puBSq+e1E8WUaSJcGY='
  );

CREATE TABLE IF NOT EXISTS skills(
  id UUID PRIMARY KEY NOT NULL,
  name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS user_skills(
  user_id UUID NOT NULL CONSTRAINT fk_users REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,
  skill_id UUID NOT NULL CONSTRAINT fk_skills REFERENCES skills (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS seniors(
  user_id UUID NOT NULL CONSTRAINT fk_users REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,
  github VARCHAR NOT NULL,
  linked_in VARCHAR NOT NULL,
  main_skill UUID NOT NULL CONSTRAINT fk_skills REFERENCES skills (id) ON UPDATE CASCADE ON DELETE CASCADE,
  suggestion VARCHAR NOT NULL
);