CREATE TABLE IF NOT EXISTS projects(
  id UUID PRIMARY KEY NOT NULL,
  repo VARCHAR NOT NULL,
  owner VARCHAR NOT NULL,
  description VARCHAR NULL
);

CREATE TABLE IF NOT EXISTS project_skills(
  project_id  UUID NOT NULL CONSTRAINT fk_projects REFERENCES projects (id) ON UPDATE CASCADE ON DELETE CASCADE,
  skill_id UUID NOT NULL CONSTRAINT fk_skills REFERENCES skills (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS labels(
  id UUID PRIMARY KEY NOT NULL,
  name VARCHAR NOT NULL,
  color VARCHAR NOT NULL,
  description VARCHAR NULL
);
